# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

def configure(conf):
	conf.env.append_value("LINKFLAGS", ["-lneo4j-client"])
	conf.env.append_value("LIB", ["neo4j-client"])
	conf.env["neo4j"] = conf.check(mandatory=True, lib='neo4j-client', uselib_store='NEO4J')
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('siot', ['internet'])
    module.use.append("NEO4J")
    module.source = [
      	'model/relationship/relationship.cc',
    	'model/siot-application.cc',
        ]

    module_test = bld.create_ns3_module_test_library('siot')
    module_test.source = [
        'test/siot-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'siot'
    headers.source = [
		'model/relationship/relationship.h',
        'model/siot-application.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

